services:
  auditoria-service:
    build: ./services/auditoria-service
    container_name: nexora_auditoria
    environment:
      PORT: 3016
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dauditoria
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.auditoria.rule=Host(`nexora-erp.e258tech.tech`) && PathPrefix(`/api/auditoria`)
      - traefik.http.routers.auditoria.entrypoints=websecure
      - traefik.http.routers.auditoria.tls=true
      - traefik.http.routers.auditoria.tls.certresolver=le
      - traefik.http.routers.auditoria.middlewares=gateway-protected@file
      - traefik.http.services.auditoria.loadbalancer.server.port=3016
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
