services:
  compras-service:
    build: ./services/compras-service
    container_name: nexora_compras
    environment:
      PORT: 3011
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dcompras
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.compras.rule=PathPrefix(`/api/compras`)
      - traefik.http.routers.compras.entrypoints=web
      - traefik.http.routers.compras.middlewares=gateway-protected@file
      - traefik.http.services.compras.loadbalancer.server.port=3011
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
