services:
  empresa-service:
    build: ./services/empresa-service
    container_name: nexora_empresa
    environment:
      PORT: 3002
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dempresa
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.empresa.rule=Host(`nexora-erp.e258tech.tech`) && PathPrefix(`/api/companies`)
      - traefik.http.routers.empresa.entrypoints=websecure
      - traefik.http.routers.empresa.tls=true
      - traefik.http.routers.empresa.tls.certresolver=le
      - traefik.http.routers.empresa.middlewares=gateway-protected@file
      - traefik.http.services.empresa.loadbalancer.server.port=3002
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
