services:
  financeiro-service:
    build: ./services/financeiro-service
    container_name: nexora_financeiro
    environment:
      PORT: 3009
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dfinanceiro
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.financeiro.rule=Host(`nexora-erp.e258tech.tech`) && PathPrefix(`/api/financeiro`)
      - traefik.http.routers.financeiro.entrypoints=websecure
      - traefik.http.routers.financeiro.tls=true
      - traefik.http.routers.financeiro.tls.certresolver=le
      - traefik.http.routers.financeiro.middlewares=gateway-protected@file
      - traefik.http.services.financeiro.loadbalancer.server.port=3009
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
