services:
  produtos-service:
    build: ./services/produtos-service
    container_name: nexora_produtos
    environment:
      PORT: 3006
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dprodutos
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.produtos.rule=Host(`nexora-erp.e258tech.tech`) && PathPrefix(`/api/produtos`)
      - traefik.http.routers.produtos.entrypoints=websecure
      - traefik.http.routers.produtos.tls=true
      - traefik.http.routers.produtos.tls.certresolver=le
      - traefik.http.routers.produtos.middlewares=gateway-protected@file
      - traefik.http.services.produtos.loadbalancer.server.port=3006
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
