services:
  seguranca-service:
    build: ./services/seguranca-service
    container_name: nexora_seguranca
    environment:
      PORT: 3020
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dseguranca
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.seguranca.rule=Host(`nexora-erp.e258tech.tech`) && PathPrefix(`/api/seguranca`)
      - traefik.http.routers.seguranca.entrypoints=websecure
      - traefik.http.routers.seguranca.tls=true
      - traefik.http.routers.seguranca.tls.certresolver=le
      - traefik.http.routers.seguranca.middlewares=gateway-protected@file
      - traefik.http.services.seguranca.loadbalancer.server.port=3020
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
