services:
  stock-service:
    build: ./services/stock-service
    container_name: nexora_stock
    environment:
      PORT: 3008
      DATABASE_URL: postgres://${DB_USER:-nexora}:${DB_PASSWORD:-nexora_pass}@db_postgres:5432/${DB_NAME:-nexora_erp}?options=-csearch_path%3Dstock
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-nexora}:${RABBITMQ_PASS:-nexora_pass}@rabbitmq:5672
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      db_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.stock.rule=Host(`nexora-erp.e258tech.tech`) && PathPrefix(`/api/stock`)
      - traefik.http.routers.stock.entrypoints=websecure
      - traefik.http.routers.stock.tls=true
      - traefik.http.routers.stock.tls.certresolver=le
      - traefik.http.routers.stock.middlewares=gateway-protected@file
      - traefik.http.services.stock.loadbalancer.server.port=3008
    networks:
      - nexora_net
    restart: unless-stopped

networks:
  nexora_net:
    driver: bridge
