-- Reverte o baseline eliminando todos os schemas e tabelas public criados.
-- ATENCAO: Esta operacao destroi todos os dados.

DROP TABLE IF EXISTS public.chat_conversas CASCADE;
DROP TABLE IF EXISTS public.chat_mensagens CASCADE;
DROP TABLE IF EXISTS public.chat_participantes CASCADE;
DROP TABLE IF EXISTS public.comunicados CASCADE;
DROP TABLE IF EXISTS public.comunicados_lidos CASCADE;
DROP TABLE IF EXISTS public.notif_colaborador CASCADE;

DROP SCHEMA IF EXISTS assinatura_digital CASCADE;
DROP SCHEMA IF EXISTS assinaturas CASCADE;
DROP SCHEMA IF EXISTS auditoria CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS autorizacao CASCADE;
DROP SCHEMA IF EXISTS centros_custo CASCADE;
DROP SCHEMA IF EXISTS clientes CASCADE;
DROP SCHEMA IF EXISTS compras CASCADE;
DROP SCHEMA IF EXISTS contabilidade CASCADE;
DROP SCHEMA IF EXISTS crm CASCADE;
DROP SCHEMA IF EXISTS empresas CASCADE;
DROP SCHEMA IF EXISTS faturacao CASCADE;
DROP SCHEMA IF EXISTS financeiro CASCADE;
DROP SCHEMA IF EXISTS gestao_escolar CASCADE;
DROP SCHEMA IF EXISTS impostos CASCADE;
DROP SCHEMA IF EXISTS logistica CASCADE;
DROP SCHEMA IF EXISTS multi_moeda CASCADE;
DROP SCHEMA IF EXISTS notifications CASCADE;
DROP SCHEMA IF EXISTS pessoas CASCADE;
DROP SCHEMA IF EXISTS pos CASCADE;
DROP SCHEMA IF EXISTS produtos CASCADE;
DROP SCHEMA IF EXISTS recrutamento CASCADE;
DROP SCHEMA IF EXISTS rh CASCADE;
DROP SCHEMA IF EXISTS saas CASCADE;
DROP SCHEMA IF EXISTS seguranca CASCADE;
DROP SCHEMA IF EXISTS sistema_configuracao CASCADE;
DROP SCHEMA IF EXISTS stock CASCADE;
DROP SCHEMA IF EXISTS tarefas CASCADE;
DROP SCHEMA IF EXISTS tesouraria CASCADE;
DROP SCHEMA IF EXISTS utilizadores CASCADE;
